### ISSUE TITLE
Add new members

### ISSUE THREAD

**Issue by jung-youjin** [gce-korea/gce-korea.github.io#11]
- Add new incoming members

Please add and edit your own member sections including your own information on the website. Create a Pull Request linking this issue (#11) once your parts are done! Welcome onboard and we are glad to have you as our crew! 🇰🇷 🎈

**CC: @kshjessica @ksg0605**

**Comment by kshjessica** [comment]
Hi! I've cloned this repository, added my section, and tried pushing the change. However, I am facing a problem of permission denial of "remote: Permission to gce-korea/gce-korea.github.io.git denied to kshjessica". 

And so, I have two questions!
1. Is the assigned issue supposed to be done as I have tried?
2. If it is, could you provide me the permission?

Thanks:)

**Comment by jung-youjin** [comment]
@kshjessica I've modified the repository setting permision from `read` to `write`. I'm sure you can push directly to the repo but I suggest creating a PR like how @ksg0605 has done! Please refer to #13

**Comment by kshjessica** [comment]
Thanks! I'll try it again😊

**Comment by jung-youjin** [comment]
Issue Closed 
- #12 
- #13
