### ISSUE TITLE
History images needs fixes :-)

### ISSUE THREAD

**Issue by sky9262** [gce-korea/gce-korea.github.io#4]
Image  <code>about/history-1</code> to <code>about/history-4</code> needs fixes

Here it's :
<code>.img-responsive{
height:auto; }</code>

But I think it should be :

<code>.img-responsive{
height:100%; }</code>

**Comment by jung-youjin** [comment]
@sky9262 Hi! Thank you for your help! Could you state **which line** and **which file** if possible? 🤣 I'm having a GCE A.M.A livestream tonight and I guess I'm in hurry HAHA Thnk you for the issue btw!!! 🙏🏼

**Comment by sky9262** [comment]
Send me link of your GCE A.M.A livestream on LinkedIn

**Comment by jung-youjin** [comment]
@sky9262 It's gonna be in Korean if you don't mind! Thanks for your interest! The link is [HERE](https://youtu.be/CAtA1nV5gdw)

**Comment by sky9262** [comment]
Oh nooo! I don't know Korean yet. :pensive:
